apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-token
  namespace: default

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubectl-job
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: kubectl-token
      containers:
      - name: kubectl
        image: falser/token:v3
        command: ["sh", "-c"]
        args: ["/pulsar/scripts/pulsar/prepare_helm_release.sh -n default -k pulsar"]
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" 标明 core API 组
  resources: ["secrets", "namespaces"]
  verbs: ["get", "watch", "list", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
# 此角色绑定允许 "jane" 读取 "default" 名字空间中的 Pod
# 你需要在该名字空间中有一个名为 “pod-reader” 的 Role
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
# 你可以指定不止一个“subject（主体）”
- kind: ServiceAccount
  name: kubectl-token # "name" 是区分大小写的
  namespace: default
roleRef:
  # "roleRef" 指定与某 Role 或 ClusterRole 的绑定关系
  kind: Role        # 此字段必须是 Role 或 ClusterRole
  name: pod-reader  # 此字段必须与你要绑定的 Role 或 ClusterRole 的名称匹配
  apiGroup: rbac.authorization.k8s.io