# permissions for end users to view pulsars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pulsar-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pulsar-operator
    app.kubernetes.io/part-of: pulsar-operator
    app.kubernetes.io/managed-by: kustomize
  name: pulsar-viewer-role
rules:
- apiGroups:
  - message.queue.my.domain
  resources:
  - pulsars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - message.queue.my.domain
  resources:
  - pulsars/status
  verbs:
  - get
