# permissions for end users to view pulsarclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pulsarcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: kustomize
  name: pulsarcluster-viewer-role
rules:
- apiGroups:
  - message.apache.com
  resources:
  - pulsarclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - message.apache.com
  resources:
  - pulsarclusters/status
  verbs:
  - get
