---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - message.apache.com
  resources:
  - pulsarclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - message.apache.com
  resources:
  - pulsarclusters/finalizers
  verbs:
  - update
- apiGroups:
  - message.apache.com
  resources:
  - pulsarclusters/status
  verbs:
  - get
  - patch
  - update
