apiVersion: message.queue.my.domain/v1alpha1
kind: Pulsar
metadata:
  labels:
    app.kubernetes.io/name: pulsar
    app.kubernetes.io/instance: pulsar-sample
    app.kubernetes.io/part-of: pulsar-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pulsar-operator
  name: pulsar-sample
spec:
  broker:
    size: 1
    image:
      repository: docker.io/apachepulsar/pulsar-all
      tag: 3.1.0
  zookeeper:
    size: 1
    storageClassName: nfs-client
    image:
      repository: docker.io/apachepulsar/pulsar-all
      tag: 3.1.0
  bookie:
    size: 1
    storageClassName: nfs-client
    image:
      repository: docker.io/apachepulsar/pulsar-all
      tag: 3.1.0
  proxy:
    size: 1
    image:
      repository: docker.io/apachepulsar/pulsar-all
      tag: 3.1.0
  autoRecovery:
    size: 0
    image:
      repository: docker.io/apachepulsar/pulsar-all
      tag: 3.1.0
  manager:
    size: 0
    image:
      repository: pulsar-manager
      tag: latest
  authentication:
    enabled: true
    provider: jwt
  monitor:
    enable: false