apiVersion: message.apache.com/v1alpha1
kind: PulsarCluster
metadata:
  labels:
    app.kubernetes.io/name: pulsarcluster
    app.kubernetes.io/instance: pulsarcluster-sample
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test
  name: pulsarcluster-sample
spec:
  broker:
    replicas: 1
  zookeeper:
    replicas: 1
    ports:
      http: 8000
      client: 2181
      # clientTls: ""
      follower: 2888
      leaderElection: 3888
    volumes:
      data:
        storageClassName: local-path
        capacity: 10Gi
    configData:
      PULSAR_MEM: >
        -Xms64m -Xmx128m
      PULSAR_GC: >
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=10
        -Dcom.sun.management.jmxremote
        -Djute.maxbuffer=10485760
        -XX:+ParallelRefProcEnabled
        -XX:+UnlockExperimentalVMOptions
        -XX:+DoEscapeAnalysis
        -XX:+DisableExplicitGC
        -XX:+ExitOnOutOfMemoryError
        -XX:+PerfDisableSharedMem
  bookie:
    replicas: 1
    journalStorageClassName: local-path
    ledgersStorageClassName: local-path
    configData:
      PULSAR_MEM: >
        -Xms128m
        -Xmx256m
        -XX:MaxDirectMemorySize=256m
      PULSAR_GC: >
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=10
        -XX:+ParallelRefProcEnabled
        -XX:+UnlockExperimentalVMOptions
        -XX:+DoEscapeAnalysis
        -XX:ParallelGCThreads=4
        -XX:ConcGCThreads=4
        -XX:G1NewSizePercent=50
        -XX:+DisableExplicitGC
        -XX:-ResizePLAB
        -XX:+ExitOnOutOfMemoryError
        -XX:+PerfDisableSharedMem
      minorCompactionThreshold: "0.2" # default 0.2 (use default)
      minorCompactionInterval: "360" # default 3600 seconds (6 minutes vs default 1 hour)
      majorCompactionThreshold: "0.8" # default 0.5
      majorCompactionInterval: "10800" # default 86400 seconds (3 hours vs default 1 day)
      gcWaitTime: "300000" # default 900000 milli-seconds (5 minutes vs default 15 minutes)
      isForceGCAllowWhenNoSpace: "true" # default false
      # disk utilization configuration
      # Make sure that diskUsageLwmThreshold <= diskUsageWarnThreshold <= diskUsageThreshold
      diskUsageLwmThreshold: "0.85" # default 0.90
      diskUsageWarnThreshold: "0.9" # default 0.95
      diskUsageThreshold: "0.95" # default 0.95 (use default)
      diskCheckInterval: "1800" # default 10000
  proxy:
    replicas: 1
  toolset:
    replicas: 1
  autoRecovery:
    replicas: 1
