apiVersion: message.apache.com/v1alpha1
kind: PulsarCluster
metadata:
  labels:
    app.kubernetes.io/name: pulsarcluster
    app.kubernetes.io/instance: pulsarcluster-sample
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test
  name: pulsarcluster-sample
spec:
  broker:
    replicas: 1
  zookeeper:
    replicas: 1
    storageClassName: hostpath
  bookie:
    replicas: 1
    storageClassName: hostpath
  proxy:
    replicas: 1

