apiVersion: message.queue.my.domain/v1alpha1
kind: Pulsar
metadata:
  labels:
    app.kubernetes.io/name: pulsar
    app.kubernetes.io/instance: pulsar-sample
    app.kubernetes.io/part-of: pulsar-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pulsar-operator
  name: pulsar-sample
spec:
  broker:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
  zookeeper:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
    storageClassName: nfs-client
  bookie:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
    storageClassName: nfs-client
  proxy:
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
    size: 1
  autoRecovery:
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
    size: 0
  manager:
    size: 0
    image:
      repository: pulsar-manager
      tag: latest
  monitor:
    enable: false